name = "kaohut-server"
compatibility_date = "2024-11-28"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "dfb567c89a194623929b6d3aa7cd7099"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"
